### ISSUE TITLE
This project is abandoned?

### ISSUE THREAD

**Issue by ctl** [FlarumJS/node-flarum#13]
It wasn't updated since fall 2016

**Comment by datitisev** [comment]
I stopped working on it because I felt like it was better to work on Flarum itself. I _may_ continue it after Flarum reaches stable, but that's unlikely.
You can see more information about why in the Flarum Community [discussion](https://discuss.flarum.org/d/2121-flarum-with-nodejs-mongodb-discontinued/29)

**Comment by ctl** [comment]
Thank you very much for explaination
